apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.myapp.example.com
spec:
  group: myapp.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      requiredCPU:
                        type: string
                      requiredMemory:
                        type: string
                      availability:
                        type: number
                preferences:
                  type: object
                  properties:
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    resourceLimit:
                      type: string
                    H:
                      type: integer
                    average:
                      type: integer
                    generation:
                      type: integer
                    numNext:
                      type: integer
                    numStart:
                      type: integer
                    rAdds:
                      type: array
                      items:
                        type: number
            status:
              type: object
              properties:
                groups:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                optimizationResult:
                  type: object
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
    shortNames:
    - acfg
