apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconfig-operator
  namespace: boutique
  labels:
    app: microservices-demo
    component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-demo
      component: operator
  template:
    metadata:
      labels:
        app: microservices-demo
        component: operator
    spec:
      serviceAccountName: appconfig-operator
      containers:
      - name: operator
        image: appconfig-operator:latest
        imagePullPolicy: Never
        command: ["kopf", "run", "/k8s-operator/k8s_operator/appconfig_operator.py", "--verbose"]
        workingDir: /app
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "DEBUG"
