# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Cart.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nCart.proto\x12\x10hipstershop.cart\"0\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"K\n\x0e\x41\x64\x64ItemRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12(\n\x04item\x18\x02 \x01(\x0b\x32\x1a.hipstershop.cart.CartItem\"#\n\x10\x45mptyCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"!\n\x0eGetCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"B\n\x04\x43\x61rt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12)\n\x05items\x18\x02 \x03(\x0b\x32\x1a.hipstershop.cart.CartItem\"\x07\n\x05\x45mpty2\xe8\x01\n\x0b\x43\x61rtService\x12\x46\n\x07\x41\x64\x64Item\x12 .hipstershop.cart.AddItemRequest\x1a\x17.hipstershop.cart.Empty\"\x00\x12\x45\n\x07GetCart\x12 .hipstershop.cart.GetCartRequest\x1a\x16.hipstershop.cart.Cart\"\x00\x12J\n\tEmptyCart\x12\".hipstershop.cart.EmptyCartRequest\x1a\x17.hipstershop.cart.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTITEM']._serialized_start=32
  _globals['_CARTITEM']._serialized_end=80
  _globals['_ADDITEMREQUEST']._serialized_start=82
  _globals['_ADDITEMREQUEST']._serialized_end=157
  _globals['_EMPTYCARTREQUEST']._serialized_start=159
  _globals['_EMPTYCARTREQUEST']._serialized_end=194
  _globals['_GETCARTREQUEST']._serialized_start=196
  _globals['_GETCARTREQUEST']._serialized_end=229
  _globals['_CART']._serialized_start=231
  _globals['_CART']._serialized_end=297
  _globals['_EMPTY']._serialized_start=299
  _globals['_EMPTY']._serialized_end=306
  _globals['_CARTSERVICE']._serialized_start=309
  _globals['_CARTSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
